### PR TITLE
Move classes from net.imglib2.img to net.imbglib2.ij

### PR DESCRIPTION
**Pull request by gab1one**
The packages  `net.imglib2.img` `net.imglib2.display.projector` and `net.imglib2.img.display`  are already contained in imglib2, therefore they should not be used here. By adding the common `ij` infix to the package names this is avoided for current and future packages.

### CODE REVIEW

**Comment by axtimwalde** [comment]
Is there a new law in town that doesn't allow me to reuse package names across artifacts?  All in favor of cleaning up and breaking historic stuff where necessary but not with this pull request which doesn't help anything but only satisfies a new arbitrary policy that I haven't subscribed to.

**Comment by tpietzsch** [comment]
Java 9 does not allow split packages in different modules.
So planning ahead to eventually modularizing the fiji world, this is a good idea...

**Comment by axtimwalde** [comment]
Ah!  Thanks for the pointer.  Then, this of course makes sense.  Java 9 spinnt!  But since nobody observed this policy before, shouldn't this be a more concerted effort across all of imglib2?

**Comment by tpietzsch** [comment]
Ideally, yes. But it can be done artifact by artifact.

Using artifact names as package prefixes seems to be a reasonable approach. So imglib2-ij goes to `net.imglib2.ij`. Other artifacts, e.g., imglib2-realtransform and imglib2-cache already follow this approach.

As a PR this is not very useful, I'm closing it and opened issue #25 instead.

**Comment by tpietzsch** [comment]
One question is what should happen to imglib2 (core) artifact.
Move everything under `net.imglib2.core`? Or just be careful not reuse any of the package names as artifact names?

**Pull request closed without merging**
