### PR TITLE
Added transformation of BitType into 8-bit ImagePlus

### PR DESCRIPTION
**Pull request by cmongis**
For some reason, Bit images where transformed into 16-bit images. I changed the ImageJFunction.wrap method so it transforms BitTypes into 8-Bit ImagePlus (common binary type
of IJ1). BitTypes of value "True" are mapped to the byte value 255.

### CODE REVIEW

**Comment by tpietzsch** [comment]
@cmongis Good catch.

Could you please format your changes with the imglib2 code style?
You can find an formatter.xml file for Eclipse here https://github.com/imglib/imglib2/blob/master/doc/imglib2-eclipse-mars-clean-up-formatter-style.xml

**Comment by cmongis** [comment]
... I used Netbeans ... I will see what I can do

**Comment by cmongis** [comment]
I found a plugin but it tend to reformat the whole file and look like I modified the whole thing. It's really disturbing. I push it nevertheless.

**Comment by tpietzsch** [comment]
Thank you very much. It looks like the `ImageJFunctions` wasn't formatted with the imglib2 style before... Sorry about the confusion.

**Comment by tpietzsch** [comment]
@cmongis I just released imglib2-ij-2.0.0-beta-34 with your fix

**Pull request merged**
