### PR TITLE
ImageJVirtualStackFloat: Don't compute minmax

### PR DESCRIPTION
**Pull request by hinerm**
Avoids iteration of the dataset when creating ImageJVirtualStackFloat instances.

### CODE REVIEW

**Comment by hinerm** [comment]
@tpietzsch Is this alright?

**Comment by tpietzsch** [comment]
@hinerm ```Float.MIN_VALUE``` is the smallest positive nonzero value of type ```float```, i.e., not the same concept as ```Integer.MIN_VALUE```. It should be either ```Float.NEGATIVE_INFINITY``` to ```Float.POSITIVE_INFINITY```, or ```-Float.MAX_VALUE``` to ```Float.MAX_VALUE```, or maybe just ```0``` to ```1```.

**Comment by hinerm** [comment]
ah of course; sorry, forgot. I like `NEGATIVE_INFINITY`/`POSITIVE_INFINITY` personally.. updated

**Comment by tpietzsch** [comment]
thanks @hinerm

**Comment by hinerm** [comment]
thanks @tpietzsch ! :octopus:

**Pull request merged**
